services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    container_name: site-nginx
    expose:
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: site-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./CaddyFile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nginx
      - 3x-ui
    restart: unless-stopped

  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    volumes:
      - xui_db:/etc/x-ui
      - xui_cert:/root/cert
    expose:
      - "2053"
      - "10001"
    ports:
      - "127.0.0.1:2124:2053"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  xui_db:
  xui_cert: